// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package squid

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "squid", asset.ModuleFieldsPri, AssetSquid); err != nil {
		panic(err)
	}
}

// AssetSquid returns asset data.
// This is the base64 encoded gzipped contents of module/squid.
func AssetSquid() string {
	return "eJysVU9P4z4QvfdTjLiTlgI/QQ8/CQFiK7FQtd2z5SaziYUTG3usJfvpV/mzaZo6aattbrGf33t+M7Yv4QPzGdhPJ6IRAAmSOIOL8v9iBBChDY3QJFQ2g/9HAFBh4buKnMQRwE+BMrKzcuoSMp7ilq74KNc4g9gop+sRD+cuTZuKhyFa2wx3Vi8kcovAo6g93kLjF091saUWsh5rofY9+ixtTRm0WmUWGYm0zdNxt6xhsBYpBju4xtfd9HpnorIiVRZ7dK0JmdD9givlTIhg8NOhJZgvfBxFbVgNYZY4OdvPuH54YW/vb88ej4Rf5OFPiHRNy0IVDcTzbb1ewKpEwmMX2QQ0nUyOD8igljmz4jcykYXSRcgS5BGaoSJpmUOxBKolIouhWtRTsqvJ/c0JnspAUqRERQM5J9uylblUC3ocvDyvTyyINopUqOSBaix8sEa2YDpeN7LEEmWpX/IJLYmMFz+wh2xUY0GJ2wShSj3aH5j/UibytkLV4c4MbLoVO0ZVBD+Wrz2pF9ufjcdbP+NUSXe3EWQ9+s4Odd2qvEQLTIH2621UukGJH7eTiZbOp5EINNyESX7opP3FDZyz9+X8Zf728MqeVic0V1HkoRupXeL5orh+ze513j5X99Pg6r+7YBJceZRClRFmxAo7/XrwWMFg3YU1MlxrKcLS0liFhHRpySBPh3uIaWUGWnlZn11nJOwhG+nrm8nt9PibI0YlfAeu+1D5nqpudCIrwttrti0pl4LbvTnNKanfjKB6ioPSVXCAMxWx4VU0ZFx3fmvMZWRyJqza7+B/sHaA9ThzUlVNch5TvWzHmTEYC5WdsX5DhEcWT1B+zobqpTspofO20iHSPmujPwEAAP//dvoUzw=="
}
